;;; Automatically generated by ‘recentf’ on Tue Feb 14 18:53:15 2017.

(setq recentf-list
      '(
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/kaogene/Documents/javascriptLearning/simple/program.html"
        "/Users/kaogene/Documents/javascriptLearning/simple/program.js"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/ac-js2-20140906.442/ac-js2-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/skewer-mode-20170122.938/skewer-mode-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/simple-httpd-20170125.1910/simple-httpd-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/js2-mode-20170202.1422/js2-mode-autoloads.el"
        "/Users/kaogene/Documents/UnrealEngine/ExamplesPractice/MyFirstApp/MyFirstApp/main.cpp"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/customizations.el"
        "/Users/kaogene/Desktop/emacsBK/Aquamacs Emacs/Preferences.el"
        "/Users/kaogene/Desktop/emacsBK/Aquamacs Emacs/customizations.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/zenburn-theme-20170103.2328/zenburn-theme-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/dracula-theme-20170210.830/dracula-theme-autoloads.el"
        "/Users/kaogene/.revive.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/frame-positions.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/projectile-20170106.606/projectile-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/ggtags-20161022.251/ggtags-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/highlight-symbol-20160102.1209/highlight-symbol-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/cpputils-cmake-20170203.155/cpputils-cmake-autoloads.el"
        "/Users/kaogene/Library/Preferences/Aquamacs Emacs/Packages/elpa/company-jedi-20151216.1921/company-jedi-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
